### ISSUE TITLE
Trying to create already existing but non-subscribed IMAP folders fails

### ISSUE THREAD

**Issue by shtrom** [spaetz/offlineimap#42]
In the course of the life of my mailbox, I create new folders for new projects. When the projects finish, I usually unsubscribe from the folder, in order not to pull it all the time, but keep it on the IMAP servers as archives.

When using a Maildir which also has this archive (regardless of its being in sync or not, I believe), offlineimap tries to create the folder on the IMAP server, which raises an error and terminates the session for that account. I think it should simply be ignored, or at least ignorable (and no sync).

ERROR: Creating folder PROJECT on repository SRV1
Folder 'PROJECT'[SRV1] could not be created. Server responded: ('NO', ['[ALREADYEXISTS] Mailbox exists.'])
ERROR: Folder 'PROJECT'[SRV1] could not be created. Server responded: ('NO', ['[ALREADYEXISTS] Mailbox exists.'])

**Comment by anarcat** [comment]
is there an issue similar to this in the new offlineimap repository? i'm still seeing this issue with 7.0.12.

**Comment by spaetz** [comment]
Hi there, I am not sure if there is a new issue on the upstream repo, but you should definitely use the upstream one, as my personal fork is obsoltete and unmaintained (I will delete it soon)

**Comment by anarcat** [comment]
understood, thanks, see https://github.com/OfflineIMAP/offlineimap/issues/443
